

spring.application.name=TravelBookingApp

spring.datasource.url=database-travel.criqmogw2ki1.ap-south-1.rds.amazonaws.com:3306/traveldb
spring.datasource.username=admin
spring.datasource.password=Deepu3946

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=8081
