pipeline {
    agent any

    environment {
        IMAGE_NAME = "sandeephalemani3946/travel-booking-app"
        IMAGE_TAG = "${BUILD_NUMBER}"
        FULL_IMAGE = "${IMAGE_NAME}:${BUILD_NUMBER}"
    }

    stages {

        stage('Checkout') {
            steps {
                git branch: 'main',
                    url: 'https://github.com/00deepureddy/travel-booking-app.git'
            }
        }

        stage('Build') {
            steps {
                sh '''
                    echo "Building application..."
                    mvn clean package -DskipTests
                '''
            }
        }

        stage('Unit Test') {
            steps {
                sh '''
                    echo "Running unit tests..."
                    mvn test
                '''
            }
        }

        stage('Build Docker Image') {
            steps {
                sh '''
                    echo "Building Docker image..."
                    docker build -t $FULL_IMAGE .
                '''
            }
        }

        stage('Push Docker Image') {
            steps {
                withCredentials([
                    usernamePassword(
                        credentialsId: 'dockerhub',
                        usernameVariable: 'DOCKER_USER',
                        passwordVariable: 'DOCKER_PASS'
                    )
                ]) {
                    sh '''
                        echo "$DOCKER_PASS" | docker login \
                            -u "$DOCKER_USER" \
                            --password-stdin

                        echo "Pushing image:"
                        echo "$FULL_IMAGE"

                        docker push "$FULL_IMAGE"

                        docker logout
                    '''
                }
            }
        }

        stage('Deploy to Kubernetes') {
            steps {
                sh '''
                    echo "Checking Kubernetes connection..."
                    kubectl get nodes

                    echo "Applying Kubernetes deployment..."
                    kubectl apply -f k8s/deployment.yaml

                    echo "Updating deployment with new Docker image..."
                    kubectl set image deployment/travel-booking-deployment \
                        travel-booking-app=$FULL_IMAGE

                    echo "Applying Kubernetes service..."
                    kubectl apply -f k8s/service.yaml

                    echo "Waiting for deployment..."
                    kubectl rollout status deployment/travel-booking-deployment

                    echo "Pods:"
                    kubectl get pods

                    echo "Services:"
                    kubectl get services
                '''
            }
        }
    }

    post {

        success {
            echo "======================================"
            echo "Pipeline executed successfully!"
            echo "Docker Image: ${FULL_IMAGE}"
            echo "======================================"
        }

        failure {
            echo "======================================"
            echo "Pipeline failed!"
            echo "======================================"
        }
    }
}
