pipeline {

    agent any

    environment {
        IMAGE_NAME = "sandeephalemani3946/travel-booking-app"
        IMAGE_TAG = "${BUILD_NUMBER}"
        FULL_IMAGE = "${IMAGE_NAME}:${IMAGE_TAG}"
    }

    stages {

        stage('Checkout') {
            steps {
                git branch: 'main',
                    url: 'https://github.com/00deepureddy/travel-booking-app.git'
            }
        }

        stage('Build') {
            steps {
                dir('travel-booking-app') {
                    sh 'mvn clean package -DskipTests'
                }
            }
        }

        stage('Unit Test') {
            steps {
                dir('travel-booking-app') {
                    sh 'mvn test'
                }
            }
        }

        stage('Build Docker Image') {
            steps {
                dir('travel-booking-app') {
                    sh 'docker build -t $IMAGE_NAME:$IMAGE_TAG .'
                }
            }
        }

        stage('Push Docker Image') {
            steps {
                withCredentials([
                    usernamePassword(
                        credentialsId: 'dockerhub',
                        usernameVariable: 'DOCKER_USER',
                        passwordVariable: 'DOCKER_PASS'
                    )
                ]) {

                    sh '''
                        echo "$DOCKER_PASS" | docker login \
                            -u "$DOCKER_USER" \
                            --password-stdin

                        docker push $IMAGE_NAME:$IMAGE_TAG

                        docker logout
                    '''
                }
            }
        }

        stage('Deploy to Kubernetes') {
            steps {
                dir('travel-booking-app') {
                    sh '''
                        kubectl apply -f k8s/deployment.yaml
                        kubectl apply -f k8s/service.yaml

                        kubectl set image deployment/travel-booking-app \
                        travel-booking-app=$IMAGE_NAME:$IMAGE_TAG

                        kubectl rollout status deployment/travel-booking-app
                    '''
                }
            }
        }
    }

    post {

        success {
            echo 'Pipeline executed successfully.'
            echo "Docker image deployed: ${FULL_IMAGE}"
        }

        failure {
            echo 'Pipeline failed.'
        }
    }
}
